### ISSUE TITLE
Windows exception when mounting

### ISSUE THREAD

**Issue by moozaad** [opendedup/sdfs#39]
```
H:\>"C:\Program Files\sdfs\mountsdfs.exe" -v cranberry-vol1  -m x -cp
cp=C:\Program Files\sdfs\bin\jre\bin\java.exe -Djava.library.path="C:\Program Files\sdfs\bin/"  -Xmx6839M -XX:+UseG1GC -Djava.awt.headless=true -server -cp "C:\Program Files\sdfs\lib\sdfs.jar";"C:\Program Files\sdfs\lib\*" org.opendedup.sdfs.windows.fs.MountSDFS -v cranberry-vol1 -m xRunning Program SDFS Version 3.4.7.1
reading config file = C:\Program Files\sdfs\etc\cranberry-vol1-volume-cfg.xml
target=https://cranberry
disableDNSBucket=true
Loading Existing Hash Tables |))))))))))))))))))))))))))))))))))))))))))))))))))| 100%

Loading BloomFilters |))))))))))))))))))))))))))))))))))))))))))))))))))| 100%

Waiting for last bloomfilters to load
ReCreating BloomFilters |))))))))))))))))))))))))))))))))))))))))))))))))))| 100%

ReCreating BloomFilters |))))))))))))))))))))))))))))))))))))))))))))))))))| 100%

Loading BloomFilters |))))))))))))))))))))))))))))))))))))))))))))))))))| 100%

Waiting for last bloomfilters to load
ReCreating BloomFilters |))))))))))))))))))))))))))))))))))))))))))))))))))| 100%

ReCreating BloomFilters |))))))))))))))))))))))))))))))))))))))))))))))))))| 100%

Waiting for all BloomFilters creation threads to finishjava.io.IOException: java.io.IOException: java.io.IOException: java.lang.NullPointerException
        at org.opendedup.collections.ShardedProgressiveFileBasedCSMap2.init(ShardedProgressiveFileBasedCSMap2.java:112)
        at org.opendedup.sdfs.filestore.HashStore.connectDB(HashStore.java:176)
        at org.opendedup.sdfs.filestore.HashStore.<init>(HashStore.java:83)
        at org.opendedup.sdfs.servers.HashChunkService.<init>(HashChunkService.java:80)
        at org.opendedup.sdfs.servers.HCServiceProxy.init(HCServiceProxy.java:202)
        at org.opendedup.sdfs.servers.SDFSService.start(SDFSService.java:78)
        at org.opendedup.sdfs.windows.fs.MountSDFS.main(MountSDFS.java:176)
Caused by: java.io.IOException: java.io.IOException: java.lang.NullPointerException
        at org.opendedup.collections.ShardedProgressiveFileBasedCSMap2.setUp(ShardedProgressiveFileBasedCSMap2.java:823)
        at org.opendedup.collections.ShardedProgressiveFileBasedCSMap2.init(ShardedProgressiveFileBasedCSMap2.java:110)
        ... 6 more
Caused by: java.io.IOException: java.lang.NullPointerException
        at org.opendedup.collections.ShardedProgressiveFileBasedCSMap2.setUp(ShardedProgressiveFileBasedCSMap2.java:815)
        ... 7 more
Caused by: java.lang.NullPointerException
        at org.opendedup.hashing.LargeBloomFilter.put(LargeBloomFilter.java:142)
        at org.opendedup.collections.LBFReconstructThread.run(LBFReconstructThread.java:41)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)

H:\>

```

Just updated, it worked before the update.

**Comment by moozaad** [comment]
Cleaned the bucket and reran it. Same error.

**Comment by moozaad** [comment]
Updated to latest version. Same error but now with an extra binding warning!

```
cp=C:\Program Files\sdfs\bin\jre\bin\java.exe -Djava.library.path="C:\Program Files\sdfs\bin/"  -Xmx9101M -XX:+UseG1GC -Djava.awt.headless=true -server -cp
reading config file = C:\Program Files\sdfs\etc\cranberry-vol1-volume-cfg.xml
SLF4J: The requested version 1.5.10 by your slf4j binding is not compatible with [1.6, 1.7]
SLF4J: See http://www.slf4j.org/codes.html#version_mismatch for further details.
target=https://cranberry.erskine-murray.co.uk
disableDNSBucket=true
Folder = s:\sdfs\volumes\cranberry-vol1\chunkstore\hdb-3605059006502349093\hashstore-sdfs
Loading Existing Hash Tables |))))))))))))))))))))))))))))))))))))))))))))))))))| 100%

Loading BloomFilters |))))))))))))))))))))))))))))))))))))))))))))))))))| 100%

Waiting for last bloomfilters to load
ReCreating BloomFilters |))))))))))))))))))))))))))))))))))))))))))))))))))| 100%

ReCreating BloomFilters |))))))))))))))))))))))))))))))))))))))))))))))))))| 100%

Loading BloomFilters |))))))))))))))))))))))))))))))))))))))))))))))))))| 100%

Waiting for last bloomfilters to load
ReCreating BloomFilters |))))))))))))))))))))))))))))))))))))))))))))))))))| 100%

ReCreating BloomFilters |))))))))))))))))))))))))))))))))))))))))))))))))))| 100%

Waiting for all BloomFilters creation threads to finishjava.io.IOException: java.io.IOException: java.io.IOException: java.lang.NullPointerException
        at org.opendedup.collections.ShardedProgressiveFileBasedCSMap2.init(ShardedProgressiveFileBasedCSMap2.java:114)
        at org.opendedup.sdfs.filestore.HashStore.connectDB(HashStore.java:176)
        at org.opendedup.sdfs.filestore.HashStore.<init>(HashStore.java:83)
        at org.opendedup.sdfs.servers.HashChunkService.<init>(HashChunkService.java:79)
        at org.opendedup.sdfs.servers.HCServiceProxy.init(HCServiceProxy.java:202)
        at org.opendedup.sdfs.servers.SDFSService.start(SDFSService.java:78)
        at org.opendedup.sdfs.windows.fs.MountSDFS.main(MountSDFS.java:176)
Caused by: java.io.IOException: java.io.IOException: java.lang.NullPointerException
        at org.opendedup.collections.ShardedProgressiveFileBasedCSMap2.setUp(ShardedProgressiveFileBasedCSMap2.java:836)
        at org.opendedup.collections.ShardedProgressiveFileBasedCSMap2.init(ShardedProgressiveFileBasedCSMap2.java:112)
        ... 6 more
Caused by: java.io.IOException: java.lang.NullPointerException
        at org.opendedup.collections.ShardedProgressiveFileBasedCSMap2.setUp(ShardedProgressiveFileBasedCSMap2.java:828)
        ... 7 more
Caused by: java.lang.NullPointerException
        at org.opendedup.hashing.LargeBloomFilter.put(LargeBloomFilter.java:142)
        at org.opendedup.collections.LBFReconstructThread.run(LBFReconstructThread.java:41)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
```

**Comment by moozaad** [comment]
Deleting the local data folder (chuckstore, ddb, files) seems to have cured the exception but now the command never returns.

```
cp=C:\Program Files\sdfs\bin\jre\bin\java.exe -Djava.library.path="C:\Program Files\sdfs\bin/"  -Xmx9101M -XX:+UseG1GC -Djava.awt.headless=true -server -cp "C:\Program Files\sdfs\lib\sdfs.jar";"C:\Program Files\sdfs\lib\*" org.opendedup.sdfs.windows.fs.MountSDFS -v cranberry-vol1 -m xRunning Program SDFS Version 3.5.2
reading config file = C:\Program Files\sdfs\etc\cranberry-vol1-volume-cfg.xml
SLF4J: The requested version 1.5.10 by your slf4j binding is not compatible with [1.6, 1.7]
SLF4J: See http://www.slf4j.org/codes.html#version_mismatch for further details.
target=https://cranberry.erskine-murray.co.uk
disableDNSBucket=true
Folder = s:\sdfs\volumes\cranberry-vol1\chunkstore\hdb-3605059006502349093\hashstore-sdfs
Loading Existing Hash Tables |))))))))))))))))))))))))))))))))))))))))))))))))))| 100%

Loading BloomFilters |))))))))))))))))))))))))))))))))))))))))))))))))))| 100%

Waiting for last bloomfilters to load
ReCreating BloomFilters |))))))))))))))))))))))))))))))))))))))))))))))))))| 100%

ReCreating BloomFilters |))))))))))))))))))))))))))))))))))))))))))))))))))| 100%

Waiting for all BloomFilters creation threads to finish done
Loaded entries 0
Running Consistancy Check on DSE, this may take a while
Scanning DSE |))))))))))))))))))))))))))))))))))))))))))))))))))| 100%

Finished
Succesfully Ran Consistance Check for [0] records, recovered [0]
```

**Comment by opendedup** [comment]
how much data is there? It may take some time to rebuild the reference
counts.

**Comment by moozaad** [comment]
Zero, both local data and ceph bucket are empty.

**Comment by opendedup** [comment]
ok cool. Rather than rebuilding the data I suggest you re-create the volume
and use the latest version of SDFS 3.5.2.

To do this:
1. uninstall the current version of SDFS
2. Make sure there is nothing in program files/sdfs/volumes/ or program
files/sdfs/etc
3. Download and install sdfs-latest.exe from
http://www.opendedup.org/downloads/sdfs-latest.exe
4. Re-create the volume

The newest version of SDFS uses a hashtable that recovers from crashes much
better than the 3.4 version.

**Comment by moozaad** [comment]
> Running Program SDFS Version 3.5.2

Wasn't a cleaned install but the rest was done. I'll try a clean install later.

**Comment by moozaad** [comment]
I didn't do the clean install yet but went back to it after a few hours and it has eventually mounted

```
Scanning DSE |))))))))))))))))))))))))))))))))))))))))))))))))))| 100%

Finished
Succesfully Ran Consistance Check for [0] records, recovered [0]
volumemounted
```
Put still hasn't returned to the prompt.

**Comment by moozaad** [comment]
Okay so it mounts consistently now I've cleaned it out but takes a really long time to do it. Neither ceph or sdfs is particularly busy in this time, reading and writing at about 17MB/s max to the ceph disk array, and a few percent CPU on both Ceph and sdfs. Is there any config worth tweaking to speed this up?

It also conflicts with the BE OST as BE thinks the FS is offline because it takes so long to mount.


```
<?xml version="1.0" encoding="UTF-8" standalone="no"?><subsystem-config version="3.4.6">
<locations dedup-db-store="s:\sdfs\volumes\cranberry-vol1\ddb" io-log="s:\sdfs\volumes\cranberry-vol1\ioperf.log"/>
<io chunk-size="256" claim-hash-schedule="0 0 12 ? * SUN" dedup-files="true" hash-type="VARIABLE_MURMUR3" log-level="1" max-file-inactive="0" max-file-write-buffers="1" max-open-files="4096" max-variable-segment-size="32" meta-file-cache="1024" read-ahead="true" safe-close="true" safe-sync="true" variable-window-size="48" volume-type="standard" write-threads="12"/>
<permissions default-file="0644" default-folder="0755" default-group="0" default-owner="0"/>

<sdfscli enable="true" enable-auth="false" listen-address="localhost" password="" port="6442" salt="" use-ssl="false"/>
<local-chunkstore allocation-size="20890720927744" average-chunk-size="8192" chunk-store="s:\sdfs\volumes\cranberry-vol1\chunkstore\chunks" chunkstore-class="org.opendedup.sdfs.filestore.BatchFileChunkStore" cluster-config="/etc/sdfs/jgroups.cfg.xml" cluster-dse-password="admin" cluster-id="sdfs-cluster" compress="true" enabled="true" encrypt="false" encryption-iv="0b6b89689407341f8f4dd131d7baaff6" encryption-key="Password" fpp=".001" gc-class="org.opendedup.sdfs.filestore.gc.PFullGC" hash-db-store="s:\sdfs\volumes\cranberry-vol1\chunkstore\hdb-3605059006502349093" hashdb-class="org.opendedup.collections.ShardedProgressiveFileBasedCSMap2" io-threads="8" low-memory="false" max-repl-batch-sz="128">
<network enable="false" hostname="0.0.0.0" port="2222" use-ssl="false"/>
<extended-config allow-sync="false" block-size="30 MB" delete-unclaimed="true" disableDNSBucket="true" glacier-archive-days="0" io-threads="16" local-cache-size="10 GB" map-cache-size="200" read-speed="0" refresh-blobs="false" simple-metadata="false" simple-s3="true" sync-check-schedule="4 59 23 * * ?" sync-files="true" upload-thread-sleep-time="10000" use-basic-signer="true" write-speed="0">
<connection-props s3-target="https://cranberry"/>
</extended-config>
<aws aws-access-key="xxxxxxxxx" aws-aim="false" aws-bucket-name="sdfs1" aws-secret-key="xxxxxxxxxxxxx" chunkstore-class="org.opendedup.sdfs.filestore.cloud.BatchAwsS3ChunkStore" enabled="true"/>
</local-chunkstore>
<volume allow-external-links="true" capacity="19 TB" closed-gracefully="false" cluster-block-copies="2" cluster-id="sdfs-cluster" cluster-rack-aware="false" cluster-response-timeout="256000" compress-metadata="false" current-size="0" dse-comp-size="0" dse-size="0" duplicate-bytes="0" files="0" maximum-percentage-full="0.95" name="cranberry-vol1" offline="false" path="s:\sdfs\volumes\cranberry-vol1\files" perf-mon-file="s:\sdfs\\logs\volume-cranberry-vol1-perf.json" read-bytes="0.0" read-timeout-seconds="-1" serial-number="3605059006502349093" sync-files="false" use-dse-capacity="true" use-dse-size="true" use-perf-mon="false" volume-clustered="false" write-bytes="0" write-timeout-seconds="-1"/></subsystem-config>
---

**Comment by moozaad** [comment]
I can seemingly get it to mount from the cmd but not via the OST connector. It basically sits looping this for hours and hours with minimal disk or cpu %. RAM on the client sits at 6GB~.

```
2017-08-17 20:13:22.652445 7fb3d9d0d700  1 civetweb: 0xbf85859000: 10.1.0.51 - - [17/Aug/2017:20:13:22 +0100] "PUT /sdfs1/bucketinfo/3605059006502349093 HTTP/1.1" 1 0 - aws-sdk-java/1.11.113 Windows_Server_2012/6.2 OpenJDK_64-Bit_Server_VM/25.121-b15/1.8.0_121 scala/2.11.7 kotlin/1.0.1
2017-08-17 20:13:26.827286 7fb3d9d0d700  1 ====== starting new request req=0x7fb3d9d07660 =====
2017-08-17 20:13:26.828443 7fb3d9d0d700  1 ====== req done req=0x7fb3d9d07660 op status=0 http_status=200 ======
2017-08-17 20:13:26.828475 7fb3d9d0d700  1 civetweb: 0xbf85859000: 10.1.0.51 - - [17/Aug/2017:20:13:22 +0100] "HEAD /sdfs1/bucketinfo/3605059006502349093 HTTP/1.1" 1 0 - aws-sdk-java/1.11.113 Windows_Server_2012/6.2 OpenJDK_64-Bit_Server_VM/25.121-b15/1.8.0_121 scala/2.11.7 kotlin/1.0.1
2017-08-17 20:13:41.835713 7fb3cbcf1700  1 ====== starting new request req=0x7fb3cbceb660 =====
2017-08-17 20:13:41.836812 7fb3cbcf1700  1 ====== req done req=0x7fb3cbceb660 op status=0 http_status=200 ======
2017-08-17 20:13:41.836877 7fb3cbcf1700  1 civetweb: 0xbf858ee000: 10.1.0.51 - - [17/Aug/2017:20:13:41 +0100] "HEAD /sdfs1/bucketinfo/3605059006502349093 HTTP/1.1" 1 0 - aws-sdk-java/1.11.113 Windows_Server_2012/6.2 OpenJDK_64-Bit_Server_VM/25.121-b15/1.8.0_121 scala/2.11.7 kotlin/1.0.1
2017-08-17 20:13:56.843483 7fb3c84ea700  1 ====== starting new request req=0x7fb3c84e4660 =====
2017-08-17 20:13:56.844779 7fb3c84ea700  1 ====== req done req=0x7fb3c84e4660 op status=0 http_status=200 ======
2017-08-17 20:13:56.844842 7fb3c84ea700  1 civetweb: 0xbf8590c000: 10.1.0.51 - - [17/Aug/2017:20:13:56 +0100] "HEAD /sdfs1/bucketinfo/3605059006502349093 HTTP/1.1" 1 0 - aws-sdk-java/1.11.113 Windows_Server_2012/6.2 OpenJDK_64-Bit_Server_VM/25.121-b15/1.8.0_121 scala/2.11.7 kotlin/1.0.1
2017-08-17 20:14:11.852902 7fb3dad0f700  1 ====== starting new request req=0x7fb3dad09660 =====
2017-08-17 20:14:11.854238 7fb3dad0f700  1 ====== req done req=0x7fb3dad09660 op status=0 http_status=200 ======
2017-08-17 20:14:11.854297 7fb3dad0f700  1 civetweb: 0xbf8584f000: 10.1.0.51 - - [17/Aug/2017:20:14:11 +0100] "HEAD /sdfs1/bucketinfo/3605059006502349093 HTTP/1.1" 1 0 - aws-sdk-java/1.11.113 Windows_Server_2012/6.2 OpenJDK_64-Bit_Server_VM/25.121-b15/1.8.0_121 scala/2.11.7 kotlin/1.0.1
2017-08-17 20:14:22.661675 7fb3cb4f0700  1 ====== starting new request req=0x7fb3cb4ea660 =====
2017-08-17 20:14:22.662912 7fb3cb4f0700  1 ====== req done req=0x7fb3cb4ea660 op status=0 http_status=200 ======
2017-08-17 20:14:22.662959 7fb3cb4f0700  1 civetweb: 0xbf858e9000: 10.1.0.51 - - [17/Aug/2017:20:14:22 +0100] "HEAD /sdfs1/bucketinfo/3605059006502349093 HTTP/1.1" 1 0 - aws-sdk-java/1.11.113 Windows_Server_2012/6.2 OpenJDK_64-Bit_Server_VM/25.121-b15/1.8.0_121 scala/2.11.7 kotlin/1.0.1
```

Last log entries are 

```
2017-08-17 18:51:13,240 [sdfs] [org.opendedup.sdfs.servers.HashChunkService] [245] [main]  - DSE did not close gracefully, running consistancy check
2017-08-17 18:51:13,434 [sdfs] [org.opendedup.sdfs.filestore.ConsistancyCheck] [25] [main]  - Running Consistancy Check on DSE, this may take a while
2017-08-17 18:51:26,452 [sdfs] [org.opendedup.sdfs.filestore.ConsistancyCheck] [73] [main]  - Succesfully Ran Consistance Check for [0] records, recovered [0]
2017-08-17 18:51:26,452 [sdfs] [org.opendedup.sdfs.servers.HCServiceProxy] [216] [main]  - running consistency check
----
2017-08-17 18:50:44,425445 | DEBUG| __cdecl SampleStorageServer::SampleStorageServer(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> >,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> >) | looking for server
2017-08-17 18:50:44,425445 | DEBUG| __cdecl SampleStorageServer::SampleStorageServer(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> >,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> >) | 1 looking for server = OpenDedupe:cranberry-vol1
2017-08-17 18:50:44,425445 | DEBUG| __cdecl SampleStorageServer::SampleStorageServer(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> >,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> >) | config file = C:\Program Files\sdfs\etc\ostconfig.xml
2017-08-17 18:50:44,425445 | DEBUG| __cdecl SampleStorageServer::SampleStorageServer(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> >,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> >) | direct=indirect mount=1 name=cranberry-vol1 enc=0
2017-08-17 18:50:44,426441 | DEBUG| __cdecl SampleLSU::SampleLSU(const char *,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> >,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> >,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> >,bool,bool,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> >) | in function
2017-08-17 18:50:44,426441 | DEBUG| __cdecl SampleLSU::SampleLSU(const char *,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> >,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> >,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> >,bool,bool,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> >) | LSU Path X:\
2017-08-17 18:50:44,426441 | DEBUG| void __cdecl CreateChildProcess(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> >) |  executing mountsdfs -v cranberry-vol1 -m X:\
```
Then nothing for 2 hours before I killed it.

**Comment by moozaad** [comment]
I'll move this into it's own ticket as it is separate from the mount exception.
