### ISSUE TITLE
AWS Cloud - default bucket location

### ISSUE THREAD

**Issue by tcf909** [opendedup/sdfs#4]
Looks like there is some issue with default-bucket-location. I can't seem to find any documentation on the setting. Here is my stack trace:

[root@STEP1 ~]# mount.sdfs -v Filesystem-cloud1 -m /opt/step/shares/Filesystem-cloud1
Running Program SDFS Version 2.0.11
reading config file = /etc/sdfs/Filesystem-cloud1-volume-cfg.xml
Initializing HashFunction
HashFunction Initialized
Unable to initiate ChunkStore
java.io.IOException: java.lang.NullPointerException
        at org.opendedup.sdfs.filestore.S3ChunkStore.init(S3ChunkStore.java:424)
        at org.opendedup.sdfs.servers.HashChunkService.<init>(HashChunkService.java:50)
        at org.opendedup.sdfs.servers.HCServiceProxy.init(HCServiceProxy.java:160)
        at org.opendedup.sdfs.servers.SDFSService.start(SDFSService.java:62)
        at fuse.SDFS.MountSDFS.main(MountSDFS.java:152)
Caused by: java.lang.NullPointerException
        at org.opendedup.sdfs.filestore.S3ChunkStore.init(S3ChunkStore.java:350)
        ... 4 more

**Comment by tcf909** [comment]
Found in a changelog the "--aws-bucket-location" option. Still should handle the lack of setting this more gracefully. Once I used the option everything seemed to mount.
