### ISSUE TITLE
volume capacity XML string setting error - get parse err from mountsdfs.exe

### ISSUE THREAD

**Issue by LarsOutzen** [opendedup/sdfs#79]
mksdfs --volume-name=sdfs_vol1 --volume-capacity=2000GB
mountsdfs -v sdfs_vol1 -m S
   _it was ok on first run yesterday  ... then today it was broken:_ 
D:\Program Files\sdfs>mountsdfs -v sdfs_vol1 -m S
Running Program SDFS Version 3.7.6.0 build date 2018-06-19 22:17
reading config file = D:\Program Files\sdfs\etc\sdfs_vol1-volume-cfg.xml
java.lang.NumberFormatException: For input string: "1,95"
        at sun.misc.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:2043)
        at sun.misc.FloatingDecimal.parseFloat(FloatingDecimal.java:122)
        at java.lang.Float.parseFloat(Float.java:451)
        at org.opendedup.util.StringUtils.parseSize(StringUtils.java:102)
        at org.opendedup.sdfs.io.Volume.<init>(Volume.java:281)
        at org.opendedup.sdfs.Config.parseSDFSConfigFile(Config.java:373)
        at org.opendedup.sdfs.servers.SDFSService.start(SDFSService.java:66)
        at org.opendedup.sdfs.windows.fs.MountSDFS.main(MountSDFS.java:161)
Exiting because java.lang.NumberFormatException: For input string: "1,95"

Workaround:
notepad D:\Program Files\sdfs\etc\sdfs_vol1-volume-cfg.xml
  _now the file again ends with the wrong setting, even after I manually fixed to "1.95 TB" so .._ 
<volume allow-external-links="true" capacity="1,95 TB" closed-gracefully="false"

**Comment by LarsOutzen** [comment]
Am using Danish local so that it the cause for the wrong write-out of a decimal-number? If the parser was in the same local, it would not be a problem. Xml should not be dependent on the local ...

**Comment by JanGruyaert** [comment]
Same problem here with Belgian locale. Created with --volume-capacity 1.5TB but in xml configuration it becomes 1,5TB which gives error when mounting. Editing workaround does work.
