### ISSUE TITLE
Path style with S3 storage ( not aws)

### ISSUE THREAD

**Issue by MourIdri** [opendedup/sdfs#8]
Hi,

Is that possible to change the path for S3 endpoint ( style and port connection)?

 mkfs.sdfs --volume-name=pool0 --volume-capacity=1TB --aws-enabled true --cloud-access-key <access-key> --cloud-secret-key <secret-key> --cloud-bucket-name <unique bucket name>

For instance, my endpoint would be something like : https://mydnsname:8082/mybucket/

Thanks

**Comment by opendedup** [comment]
To use a generic s3 endpoint use the following command

sudo mkfs.sdfs --volume-name=pool0 --volume-capacity=1TB --aws-enabled true
--cloud-access-key <access-key> --cloud-secret-key <secret-key>
--cloud-disable-test --cloud-bucket-name <unique bucket name> --cloud-url
<the url of the s3 target>

**Comment by MourIdri** [comment]
Thanks for the reply. I do not see in the "man" how to skip the ssl validation.. I am doing it for internal validation : 

Caused by: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
        at sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:387)
        at sun.security.validator.PKIXValidator.engineValidate(PKIXValidator.java:292)
        at sun.security.validator.Validator.validate(Validator.java:260)
        at sun.security.ssl.X509TrustManagerImpl.validate(X509TrustManagerImpl.java:324)
        at sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:229)
        at sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(X509TrustManagerImpl.java:124)
        at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1491)

**Comment by opendedup** [comment]
Hi - can you share your sdfs xml config? I can review it and let you know
what needs to be done. When using a generic s3 target is should ignore all
ssl warnings.

**Comment by MourIdri** [comment]
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<subsystem-config version="3.1.9">
<locations dedup-db-store="/opt/sdfs/volumes/dedupfstest4/ddb" io-log="/opt/sdfs/volumes/dedupfstest4/ioperf.log"/>
<io chunk-size="256" claim-hash-schedule="0 59 23 * * ?" dedup-files="true" hash-type="VARIABLE_MURMUR3" log-level="1" max-file-inactive="900" max-file-write-buffers="1" ma$
<permissions default-file="0644" default-folder="0755" default-group="0" default-owner="0"/>
<volume capacity="100MB" closed-gracefully="true" cluster-block-copies="2" cluster-id="sdfs-cluster" cluster-rack-aware="false" cluster-response-timeout="256000" current-si$
<sdfscli enable="true" enable-auth="false" listen-address="localhost" password="b14cff8528a11e70697c7b36bc2955706c48a77b88fc61c1ed6ba4f747de880b" port="6442" salt="7igtjG"/>
<local-chunkstore allocation-size="104857600" average-chunk-size="8192" chunk-store="/opt/sdfs/volumes/dedupfstest4/chunkstore/chunks" chunkstore-class="org.opendedup.sdfs.$
<network enable="false" hostname="0.0.0.0" port="2222" use-ssl="false"/>
<extended-config allow-sync="false" block-size="20 MB" delete-unclaimed="true" disableDNSBucket="true" glacier-archive-days="0" io-threads="16" local-cache-size="10GB" map-$
<connection-props s3-target="https://lab-g1.demofr.mygrid.fr:8082/fuses3/"/>
</extended-config>
<aws aws-access-key="3ZFX7HXU1LEVLDKMFW92" aws-aim="false" aws-bucket-name="fuses3" aws-secret-key="RxsO1LCqQvzBZvMyM4AXPHSGtGuK0GbKk46XaRi0" chunkstore-class="org.opendedu$
</local-chunkstore>
</subsystem-config>

**Comment by MourIdri** [comment]
<?xml version="1.0" encoding="UTF-8" standalone="no"?>

<subsystem-config version="3.1.9">

<locations dedup-db-store="/opt/sdfs/volumes/dedupfstest4/ddb" io-log="/opt/sdfs/volumes/dedupfstest4/ioperf.log"/>

<io chunk-size="256" claim-hash-schedule="0 59 23 * * ?" dedup-files="true" hash-type="VARIABLE_MURMUR3" log-level="1" max-file-inactive="900" max-file-write-buffers="1" ma$

<permissions default-file="0644" default-folder="0755" default-group="0" default-owner="0"/>

<volume capacity="100MB" closed-gracefully="true" cluster-block-copies="2" cluster-id="sdfs-cluster" cluster-rack-aware="false" cluster-response-timeout="256000" current-si$

<sdfscli enable="true" enable-auth="false" listen-address="localhost" password="b14cff8528a11e70697c7b36bc2955706c48a77b88fc61c1ed6ba4f747de880b" port="6442" salt="7igtjG"/>

<local-chunkstore allocation-size="104857600" average-chunk-size="8192" chunk-store="/opt/sdfs/volumes/dedupfstest4/chunkstore/chunks" chunkstore-class="org.opendedup.sdfs.$
<network enable="false" hostname="0.0.0.0" port="2222" use-ssl="false"/>

<extended-config allow-sync="false" block-size="20 MB" delete-unclaimed="true" disableDNSBucket="true" glacier-archive-days="0" io-threads="16" local-cache-size="10GB" map-$

<connection-props s3-target="https://lab-g1.demofr.mygrid.fr:8082/fuses3/"/>

</extended-config>

<aws aws-access-key="3ZFX7HXU1LEVLDKMFW92" aws-aim="false" aws-bucket-name="fuses3" aws-secret-key="RxsO1LCqQvzBZvMyM4AXPHSGtGuK0GbKk46XaRi0" chunkstore-class="org.opendedu$
</local-chunkstore>

</subsystem-config>

**Comment by MourIdri** [comment]
`####################################******************************
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<subsystem-config version="3.1.9">
<locations dedup-db-store="/opt/sdfs/volumes/dedupfstest4/ddb" io-log="/opt/sdfs/volumes/dedupfstest4/ioperf.log"/>
<io chunk-size="256" claim-hash-schedule="0 59 23 * * ?" dedup-files="true" hash-type="VARIABLE_MURMUR3" log-level="1" max-file-inactive="900" max-file-write-buffers="1" ma$
<permissions default-file="0644" default-folder="0755" default-group="0" default-owner="0"/>
<volume capacity="100MB" closed-gracefully="true" cluster-block-copies="2" cluster-id="sdfs-cluster" cluster-rack-aware="false" cluster-response-timeout="256000" current-si$
<sdfscli enable="true" enable-auth="false" listen-address="localhost" password="b14cff8528a11e70697c7b36bc2955706c48a77b88fc61c1ed6ba4f747de880b" port="6442" salt="7igtjG"/>
<local-chunkstore allocation-size="104857600" average-chunk-size="8192" chunk-store="/opt/sdfs/volumes/dedupfstest4/chunkstore/chunks" chunkstore-class="org.opendedup.sdfs.$
<network enable="false" hostname="0.0.0.0" port="2222" use-ssl="false"/>
<extended-config allow-sync="false" block-size="20 MB" delete-unclaimed="true" disableDNSBucket="true" glacier-archive-days="0" io-threads="16" local-cache-size="10GB" map-$
<connection-props s3-target="https://lab-g1.demofr.mygrid.fr:8082/fuses3/"/>
</extended-config>
<aws aws-access-key="3ZFX7HXU1LEVLDKMFW92" aws-aim="false" aws-bucket-name="fuses3" aws-secret-key="RxsO1LCqQvzBZvMyM4AXPHSGtGuK0GbKk46XaRi0" chunkstore-class="org.opendedu$
</local-chunkstore>
</subsystem-config>
####################################******************************`

**Comment by opendedup** [comment]
Can you try this jar and let me know if it works. copy it into
/usr/share/sdfs/lib/sdfs.jar

**Comment by opendedup** [comment]
Please download this jar and give it a try. Copy it to /usr/share/sdfs/lib/

http://www.opendedup.org/downloads/sdfs.jar

**Comment by MourIdri** [comment]
Thank you. I tried, but still same issue. 

Here is the complete procedure I am doing :  

`root@debianfuse:~# sudo mkfs.sdfs --volume-name=opendedups3 --volume-capacity=1GB --aws-enabled true --cloud-access-key 3ZFX7HXU1LEVLDKMFW92 --cloud-secret-key RxsO1LCqQvzBZvMyM4AXPHSGtGuK0GbKk46XaRi0 --cloud-bucket-name opendedups3 --cloud-url https://lab-g1.demofr.mydnsname.fr:8082/  --cloud-disable-test --chunk-store-encrypt=false
Attempting to create SDFS volume ...
Volume [opendedups3] created with a capacity of [1GB]
check [/etc/sdfs/opendedups3-volume-cfg.xml] for configuration details if you need to change anything


root@debianfuse:~# mkdir -p /mnt/opendedups3
root@debianfuse:~# sudo mount -t sdfs opendedups3 /mnt/opendedups3
root@debianfuse:~# Running Program SDFS Version 3.1.11
reading config file = /etc/sdfs/opendedups3-volume-cfg.xml
09:56:37.053     main  INFO [com.amazonaws.http.AmazonHttpClient]: Unable to execute HTTP request: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
        at sun.security.ssl.Alerts.getSSLException(Alerts.java:192)
        at sun.security.ssl.SSLSocketImpl.fatal(SSLSocketImpl.java:1949)
        at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:302)
        at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:296)
        at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1509)
        at sun.security.ssl.ClientHandshaker.processMessage(ClientHandshaker.java:216)
        at sun.security.ssl.Handshaker.processLoop(Handshaker.java:979)
        at sun.security.ssl.Handshaker.process_record(Handshaker.java:914)
        at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:1062)
        at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1375)
        at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1403)
        at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1387)
        at org.apache.http.conn.ssl.SSLSocketFactory.connectSocket(SSLSocketFactory.java:535)
        at org.apache.http.conn.ssl.SSLSocketFactory.connectSocket(SSLSocketFactory.java:403)
        at com.amazonaws.http.conn.ssl.SdkTLSSocketFactory.connectSocket(SdkTLSSocketFactory.java:134)
        at org.apache.http.impl.conn.DefaultClientConnectionOperator.openConnection(DefaultClientConnectionOperator.java:177)
        at org.apache.http.impl.conn.ManagedClientConnectionImpl.open(ManagedClientConnectionImpl.java:304)
        at org.apache.http.impl.client.DefaultRequestDirector.tryConnect(DefaultRequestDirector.java:611)
        at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:446)
        at org.apache.http.impl.client.AbstractHttpClient.doExecute(AbstractHttpClient.java:863)
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82)
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:57)
        at com.amazonaws.http.AmazonHttpClient.executeOneRequest(AmazonHttpClient.java:860)
        at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:631)
        at com.amazonaws.http.AmazonHttpClient.doExecute(AmazonHttpClient.java:400)
        at com.amazonaws.http.AmazonHttpClient.executeWithTimer(AmazonHttpClient.java:362)
        at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:311)
        at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:3674)
        at com.amazonaws.services.s3.AmazonS3Client.headBucket(AmazonS3Client.java:1102)
        at com.amazonaws.services.s3.AmazonS3Client.doesBucketExist(AmazonS3Client.java:1060)
        at org.opendedup.sdfs.filestore.cloud.BatchAwsS3ChunkStore.init(BatchAwsS3ChunkStore.java:412)
        at org.opendedup.sdfs.servers.HashChunkService.<init>(HashChunkService.java:50)
        at org.opendedup.sdfs.servers.HCServiceProxy.init(HCServiceProxy.java:160)
        at org.opendedup.sdfs.servers.SDFSService.start(SDFSService.java:58)
        at fuse.SDFS.MountSDFS.setup(MountSDFS.java:203)
        at fuse.SDFS.MountSDFS.init(MountSDFS.java:238)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.commons.daemon.support.DaemonLoader.load(DaemonLoader.java:207)
Caused by: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
        at sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:387)
        at sun.security.validator.PKIXValidator.engineValidate(PKIXValidator.java:292)
        at sun.security.validator.Validator.validate(Validator.java:260)
        at sun.security.ssl.X509TrustManagerImpl.validate(X509TrustManagerImpl.java:324)
        at sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:229)
        at sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(X509TrustManagerImpl.java:124)
        at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1491)
        ... 36 more
Caused by: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
        at sun.security.provider.certpath.SunCertPathBuilder.build(SunCertPathBuilder.java:141)
        at sun.security.provider.certpath.SunCertPathBuilder.engineBuild(SunCertPathBuilder.java:126)
        at java.security.cert.CertPathBuilder.build(CertPathBuilder.java:280)
        at sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:382)
        ... 42 more
`

**Comment by opendedup** [comment]
I think this has been fixed. Can you please download the sdfs.jar again
from http://www.opendedup.org/downloads/sdfs.jar and try it again. Thanks !

**Comment by MourIdri** [comment]
It works Great Now ! 
Thank you.

**Comment by opendedup** [comment]
Thanks I will release this in the next update.
