### ISSUE TITLE
SDFS not returning diskspace (chunkstore\chunks)

### ISSUE THREAD

**Issue by richman1000000** [opendedup/sdfs#88]
SDFS not returning disk space and keeps growing.

**Comment by richman1000000** [comment]
User XFS for this.
 EXT4 have limit of some descriptions

**Comment by richman1000000** [comment]
nope. After 3 month of backups - i deleted all files copy of files (5.9TB original data). Disk space on underlying FS (xfs) is still busy by SDFS folder.

**Comment by richman1000000** [comment]
I found something in chunkstore
10040855587453560 - this is chunk of file i deleted

10040855587453560.md  - it says "deleted-objectst"
10040855587453560.cmap and 10040855587453560.map is 500KB for block of 4 KB!!!!

[10040855587453560.zip](https://github.com/opendedup/sdfs/files/2806828/10040855587453560.zip)

**Comment by richman1000000** [comment]
a way to reproduce it.

1. create new local sdfs volume - “sdfs01”
2. mount and umount it.
3. check size of chunkstore
![image](https://user-images.githubusercontent.com/9943374/62539348-b2a2e500-b85d-11e9-946f-59169a5ee663.png)


4. mount it again.
5. copy files on SDFS volume. 


debian-10.0.0-amd64-xfce-CD-1.iso (641M, you can get it from https://debian.org) three times.
CentOS-7-x86_64-DVD-1810.iso 90 (4Gb, you can get it from https://www.centos.org) once.


6. Chunk store grown as expected and deduplicated this copies.
![image](https://user-images.githubusercontent.com/9943374/62539361-b9315c80-b85d-11e9-8da0-3a9a841913ec.png)
7. remove all files from sdfs volume.
8. check sizes of chunkstore.
![image](https://user-images.githubusercontent.com/9943374/62539383-c77f7880-b85d-11e9-828a-2b136d3f1fc0.png)


9. run command “sdfscli --compactcleanstore=0 –cleanstore=0” or  “sdfscli --compactcleanstore=1 –cleanstore=1” 

10. check size of chunkstore again
![image](https://user-images.githubusercontent.com/9943374/62539388-ca7a6900-b85d-11e9-9caa-a338e18d0a58.png)


Result: folder chunks is not reducing in size, whatever i tried.

Expected: if chunk is not used it must be removed from physical  disk after some time(define in config) or immediately(preferred, but maybe 1 minute later can be accepted). 

PS.
my test environment VM Debian 10, 4CPU, 12GB RAM, 24GB disk, 12GB sdfs volume,  
![image](https://user-images.githubusercontent.com/9943374/62539395-cd755980-b85d-11e9-846a-b68c51bb0961.png)

**Comment by opendedup** [comment]
I will validate this today

**Comment by richman1000000** [comment]
so, did you reproduced it?

**Comment by richman1000000** [comment]
![image](https://user-images.githubusercontent.com/9943374/74106248-1e03a180-4b76-11ea-9035-a65f1dc052ca.png)
I found strange exception in log files.

**Comment by richman1000000** [comment]
This exception is constantly appears in log files now. 
```
2020-03-06 12:00:07,323 [ERROR] [sdfs] [org.opendedup.sdfs.filestore.HashBlobArchive] [2170] [Thread-2]  - unable to compact 738290221524246209
java.nio.channels.ClosedChannelException
        at java.base/sun.nio.ch.FileChannelImpl.ensureOpen(FileChannelImpl.java:150)
        at java.base/sun.nio.ch.FileChannelImpl.size(FileChannelImpl.java:373)
        at org.opendedup.collections.SimpleByteArrayLongMap.next(SimpleByteArrayLongMap.java:142)
        at org.opendedup.sdfs.filestore.HashBlobArchive.compact(HashBlobArchive.java:2085)
        at org.opendedup.sdfs.filestore.HashBlobArchive.compactArchive(HashBlobArchive.java:973)
        at org.opendedup.sdfs.filestore.BatchFileChunkStore.run(BatchFileChunkStore.java:436)
        at java.base/java.lang.Thread.run(Thread.java:834)
2020-03-06 12:00:07,370 [INFO] [sdfs] [org.opendedup.sdfs.filestore.BatchFileChunkStore] [433] [Thread-2]  - updating 4744508249846398533 sz=1
2020-03-06 12:00:07,434 [ERROR] [sdfs] [org.opendedup.sdfs.filestore.HashBlobArchive] [2170] [Thread-2]  - unable to compact 4744508249846398533
java.nio.channels.ClosedChannelException
        at java.base/sun.nio.ch.FileChannelImpl.ensureOpen(FileChannelImpl.java:150)
        at java.base/sun.nio.ch.FileChannelImpl.size(FileChannelImpl.java:373)
        at org.opendedup.collections.SimpleByteArrayLongMap.next(SimpleByteArrayLongMap.java:142)
        at org.opendedup.sdfs.filestore.HashBlobArchive.compact(HashBlobArchive.java:2085)
        at org.opendedup.sdfs.filestore.HashBlobArchive.compactArchive(HashBlobArchive.java:973)
        at org.opendedup.sdfs.filestore.BatchFileChunkStore.run(BatchFileChunkStore.java:436)
        at java.base/java.lang.Thread.run(Thread.java:834)

```

**Comment by richman1000000** [comment]
I found it!!

in SDFS xml config change set
<local-chunkstore  **sync-files="true"** />
<volume  **sync-files="true"** />

after this run 

sdfscli --compactcleanstore
sdfscli  --cleanstore
sdfscli --compactcleanstore
sdfscli --sync-fs-size

**Comment by dima333750** [comment]
I have exactly the same problem on windows 10, I use the default settings, when I delete a file it takes up space (I waited a long time, I thought asynchronous deletion)
This is terribly sad because completely makes sense of use!
I tried:
<local-chunkstore sync-files = "true" />
<volume sync-files = "true" />

after this run

sdfscli --compactcleanstore
sdfscli --cleanstore
sdfscli --compactcleanstore
sdfscli --sync-fs-size
But mine just started to corrupt the file when writing.

**Comment by richman1000000** [comment]
I cann't tell anything about windows version. I tried it and it fails to start. So, I'm running opendedup only on Linux

**Comment by looopTools** [comment]
I have a similar problem on Ubuntu. 
But changing 

```
<local-chunkstore sync-files="true" />
<volume sync-files="true" />
```

and then running 

```
sdfscli --compactcleanstore
sdfscli --cleanstore
sdfscli --compactcleanstore
sdfscli --sync-fs-size
```

did not solve my isssue

**Comment by richman1000000** [comment]
Can you check in log files if you have error?
` [ERROR] [sdfs] [org.opendedup.sdfs.filestore.HashBlobArchive] [2170] [Thread-2]  - unable to compact 738290221524246209`

**Comment by richman1000000** [comment]
@opendedup  I've checked with latest 3.11 sdfs version.
unfortunately  "chunks" folder  still not being  shrunk . 
![image](https://user-images.githubusercontent.com/9943374/103273061-71215580-49cf-11eb-96ea-b4189a9683f7.png)
![image](https://user-images.githubusercontent.com/9943374/103273205-c5c4d080-49cf-11eb-8a18-f0f8a0adc7ec.png)

**Comment by dima333750** [comment]
Это проблема продолжает сохраняться на версии 3.7.8 на windows 10 1809.
Проблема легко возпрозводится на настройках по умолчанию:
```
mksdfs --volume-name=deduram --volume-capacity=50GB
mountsdfs -v deduram -m x

```
В log я нашел такие данные: 
```
ERROR_FILE_NOT_FOUND
	at org.opendedup.sdfs.windows.fs.WinSDFS.resolvePath(WinSDFS.java:868)
	at org.opendedup.sdfs.windows.fs.WinSDFS.getFileChannel(WinSDFS.java:793)
	at org.opendedup.sdfs.windows.fs.WinSDFS$DeleteFileThread.run(WinSDFS.java:1112)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
2021-02-06 09:14:49,236 [ERROR] [fs] [org.opendedup.sdfs.windows.fs.WinSDFS] [624] [Thread-25]  - unable to delete file \chrome_child.dll
ERROR_FILE_NOT_FOUND
	at org.opendedup.sdfs.windows.fs.WinSDFS.resolvePath(WinSDFS.java:868)
	at org.opendedup.sdfs.windows.fs.WinSDFS.getFileChannel(WinSDFS.java:793)
	at org.opendedup.sdfs.windows.fs.WinSDFS$DeleteFileThread.run(WinSDFS.java:1112)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
2021-02-06 09:14:49,445 [INFO] [sdfs] [org.opendedup.collections.LongByteArrayMap] [894] [pool-3-thread-1]  - Opens for C:\Program Files\sdfs\volumes\deduram\ddb\50\50b5e43b-2eeb-4d07-b9fe-ec9390dc740d\50b5e43b-2eeb-4d07-b9fe-ec9390dc740d.map = -1
2021-02-06 09:15:27,435 [ERROR] [fs] [org.opendedup.sdfs.windows.fs.WinSDFS$DeleteFolderThread] [1152] [pool-4-thread-10]  - unable to delete folder C:\Program Files\sdfs\volumes\deduram\files\1
2021-02-06 09:15:27,435 [ERROR] [fs] [org.opendedup.sdfs.windows.fs.WinSDFS] [660] [Thread-38]  - unable to delete directory \1
ERROR_DIR_NOT_EMPTY
	at org.opendedup.sdfs.windows.fs.WinSDFS$DeleteFolderThread.run(WinSDFS.java:1153)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
2021-02-06 09:15:27,442 [INFO] [sdfs] [org.opendedup.sdfs.io.SparseDedupFile] [875] [pool-4-thread-10]  - Channel size is 0
2021-02-06 09:15:27,443 [INFO] [sdfs] [org.opendedup.sdfs.io.SparseDedupFile] [877] [pool-4-thread-10]  - Closinging C:\Program Files\sdfs\volumes\deduram\files\1\chrome.dll
2021-02-06 09:15:27,443 [INFO] [sdfs] [org.opendedup.collections.LongByteArrayMap] [894] [pool-4-thread-10]  - Opens for C:\Program Files\sdfs\volumes\deduram\ddb\ba\ba4c2dbe-fc1e-4def-908d-1f5a9e7c2c48\ba4c2dbe-fc1e-4def-908d-1f5a9e7c2c48.map = 0
2021-02-06 09:15:27,444 [ERROR] [fs] [org.opendedup.sdfs.windows.fs.WinSDFS] [624] [Thread-31]  - unable to delete file \1\chrome.dll
```

**Comment by dima333750** [comment]
Log files
[deduram-volume-cfg.log](https://github.com/opendedup/sdfs/files/5936374/deduram-volume-cfg.log)

**Comment by richman1000000** [comment]
> 
> 
> Это проблема продолжает сохраняться на версии 3.7.8 на windows 10 1809.
> Проблема легко возпрозводится на настройках по умолчанию:
> 
> ```
> mksdfs --volume-name=deduram --volume-capacity=50GB
> mountsdfs -v deduram -m x
> ```
> 
> В log я нашел такие данные:
> 
> ```
> ERROR_FILE_NOT_FOUND
> 	at org.opendedup.sdfs.windows.fs.WinSDFS.resolvePath(WinSDFS.java:868)
> 	at org.opendedup.sdfs.windows.fs.WinSDFS.getFileChannel(WinSDFS.java:793)
> 	at org.opendedup.sdfs.windows.fs.WinSDFS$DeleteFileThread.run(WinSDFS.java:1112)
> 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
> 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
> 	at java.lang.Thread.run(Thread.java:748)
> 2021-02-06 09:14:49,236 [ERROR] [fs] [org.opendedup.sdfs.windows.fs.WinSDFS] [624] [Thread-25]  - unable to delete file \chrome_child.dll
> ERROR_FILE_NOT_FOUND
> 	at org.opendedup.sdfs.windows.fs.WinSDFS.resolvePath(WinSDFS.java:868)
> 	at org.opendedup.sdfs.windows.fs.WinSDFS.getFileChannel(WinSDFS.java:793)
> 	at org.opendedup.sdfs.windows.fs.WinSDFS$DeleteFileThread.run(WinSDFS.java:1112)
> 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
> 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
> 	at java.lang.Thread.run(Thread.java:748)
> 2021-02-06 09:14:49,445 [INFO] [sdfs] [org.opendedup.collections.LongByteArrayMap] [894] [pool-3-thread-1]  - Opens for C:\Program Files\sdfs\volumes\deduram\ddb\50\50b5e43b-2eeb-4d07-b9fe-ec9390dc740d\50b5e43b-2eeb-4d07-b9fe-ec9390dc740d.map = -1
> 2021-02-06 09:15:27,435 [ERROR] [fs] [org.opendedup.sdfs.windows.fs.WinSDFS$DeleteFolderThread] [1152] [pool-4-thread-10]  - unable to delete folder C:\Program Files\sdfs\volumes\deduram\files\1
> 2021-02-06 09:15:27,435 [ERROR] [fs] [org.opendedup.sdfs.windows.fs.WinSDFS] [660] [Thread-38]  - unable to delete directory \1
> ERROR_DIR_NOT_EMPTY
> 	at org.opendedup.sdfs.windows.fs.WinSDFS$DeleteFolderThread.run(WinSDFS.java:1153)
> 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
> 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
> 	at java.lang.Thread.run(Thread.java:748)
> 2021-02-06 09:15:27,442 [INFO] [sdfs] [org.opendedup.sdfs.io.SparseDedupFile] [875] [pool-4-thread-10]  - Channel size is 0
> 2021-02-06 09:15:27,443 [INFO] [sdfs] [org.opendedup.sdfs.io.SparseDedupFile] [877] [pool-4-thread-10]  - Closinging C:\Program Files\sdfs\volumes\deduram\files\1\chrome.dll
> 2021-02-06 09:15:27,443 [INFO] [sdfs] [org.opendedup.collections.LongByteArrayMap] [894] [pool-4-thread-10]  - Opens for C:\Program Files\sdfs\volumes\deduram\ddb\ba\ba4c2dbe-fc1e-4def-908d-1f5a9e7c2c48\ba4c2dbe-fc1e-4def-908d-1f5a9e7c2c48.map = 0
> 2021-02-06 09:15:27,444 [ERROR] [fs] [org.opendedup.sdfs.windows.fs.WinSDFS] [624] [Thread-31]  - unable to delete file \1\chrome.dll
> ```

This is different topic. It is in another ticket.
Это другая ошибка. Она в другом тикете.

**Comment by richman1000000** [comment]
In new version "3.12" 
I've tested this scenario again. Now space being returned, but only until this error.

![image](https://user-images.githubusercontent.com/9943374/116968217-b70f6280-acbc-11eb-918f-1e27a9f68df2.png)
after this error appears "chunks" stopped being removed.

**Comment by richman1000000** [comment]
Work!
after several hours uptime of volume and executing
`startsdfs -c -f /etc/sdfs/test-volume-cfg.xml -m /media/test`
re-mounting this way it finally works
