### ISSUE TITLE
how to extend a sdfs volume

### ISSUE THREAD

**Issue by li-jun-fei** [opendedup/sdfs#93]
I created a sdfs fuse volume 1TB capacity.now is full, to fix it, I have extended the unerlay LVM and EXT4 filesystem. but I got no idea to extend the sdfs volume.

**Comment by inforhunter** [comment]
sdfscli --expandvolume

**Comment by greend139** [comment]
This does not work for me.  When trying to expand the volume i get.

```
# sdfscli --expandvolume 2TB
expanding volume to [2TB]
java.io.IOException: java.io.IOException: java.lang.IllegalArgumentException: Empty key
        at org.opendedup.sdfs.mgmt.cli.MgmtServerConnection.getResponse(MgmtServerConnection.java:179)
        at org.opendedup.sdfs.mgmt.cli.ProcessXpandVolumeCmd.runCmd(ProcessXpandVolumeCmd.java:18)
        at org.opendedup.sdfs.mgmt.cli.SDFSCmdline.parseCmdLine(SDFSCmdline.java:261)
        at org.opendedup.sdfs.mgmt.cli.SDFSCmdline.main(SDFSCmdline.java:678)
Caused by: java.io.IOException: java.lang.IllegalArgumentException: Empty key
        at org.opendedup.sdfs.mgmt.cli.MgmtServerConnection.createAuthUrl(MgmtServerConnection.java:123)
        at org.opendedup.sdfs.mgmt.cli.MgmtServerConnection.getResponse(MgmtServerConnection.java:155)
        ... 3 more
Caused by: java.lang.IllegalArgumentException: Empty key
        at javax.crypto.spec.SecretKeySpec.<init>(SecretKeySpec.java:96)
        at org.opendedup.hashing.HashFunctions.getHmacSHA256(HashFunctions.java:259)
        at org.opendedup.sdfs.mgmt.cli.MgmtServerConnection.createAuthUrl(MgmtServerConnection.java:111)
        ... 4 more
```
